// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAGkyDLHTah5tF7SklCmeiKHnIZT0gViHQ',
//     appId: '1:742047168744:web:ba43124ee24d05b57fb15d',
//     messagingSenderId: '742047168744',
//     projectId: 'camocam-ce6fb',
//     authDomain: 'camocam-ce6fb.firebaseapp.com',
//     storageBucket: 'camocam-ce6fb.firebasestorage.app',
//     measurementId: 'G-3J9DHPG31T',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCU6DPdrEmMIstiHiLuI075OJRhaVK2HPg',
//     appId: '1:742047168744:android:b64dee0dd39251d57fb15d',
//     messagingSenderId: '742047168744',
//     projectId: 'camocam-ce6fb',
//     storageBucket: 'camocam-ce6fb.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBFUn23L4To0nxPEoJvjXLu1wGs0t5G1mM',
//     appId: '1:742047168744:ios:75cfd1b2657e8f6c7fb15d',
//     messagingSenderId: '742047168744',
//     projectId: 'camocam-ce6fb',
//     storageBucket: 'camocam-ce6fb.firebasestorage.app',
//     iosClientId: '742047168744-ukio0ogiotkoj7eiotjrh41p6ar9utbg.apps.googleusercontent.com',
//     iosBundleId: 'com.example.camocam',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBFUn23L4To0nxPEoJvjXLu1wGs0t5G1mM',
//     appId: '1:742047168744:ios:75cfd1b2657e8f6c7fb15d',
//     messagingSenderId: '742047168744',
//     projectId: 'camocam-ce6fb',
//     storageBucket: 'camocam-ce6fb.firebasestorage.app',
//     iosClientId: '742047168744-ukio0ogiotkoj7eiotjrh41p6ar9utbg.apps.googleusercontent.com',
//     iosBundleId: 'com.example.camocam',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAGkyDLHTah5tF7SklCmeiKHnIZT0gViHQ',
//     appId: '1:742047168744:web:9d2070e04e0464d67fb15d',
//     messagingSenderId: '742047168744',
//     projectId: 'camocam-ce6fb',
//     authDomain: 'camocam-ce6fb.firebaseapp.com',
//     storageBucket: 'camocam-ce6fb.firebasestorage.app',
//     measurementId: 'G-TZ105X7GM0',
//   );
// }
